ERROR - 2023-04-26 11:21:07 --> ErrorException: pg_query(): Query failed: ERROR:  relation "tbl_data_point" already exists in C:\xampp\htdocs\petalokasiobjek\system\Database\Postgre\Connection.php:147
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 147)
#1 C:\xampp\htdocs\petalokasiobjek\system\Database\Postgre\Connection.php(147): pg_query(Object(PgSql\Connection), 'CREATE TABLE "t...')
#2 C:\xampp\htdocs\petalokasiobjek\system\Database\BaseConnection.php(691): CodeIgniter\Database\Postgre\Connection->execute('CREATE TABLE "t...')
#3 C:\xampp\htdocs\petalokasiobjek\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE "t...')
#4 C:\xampp\htdocs\petalokasiobjek\system\Database\Forge.php(546): CodeIgniter\Database\BaseConnection->query('CREATE TABLE "t...')
#5 C:\xampp\htdocs\petalokasiobjek\app\Database\Migrations\2023-04-17-084000_TabelDataPoint.php(48): CodeIgniter\Database\Forge->createTable('tbl_data_point')
#6 C:\xampp\htdocs\petalokasiobjek\system\Database\MigrationRunner.php(877): App\Database\Migrations\TabelDataPoint->up()
#7 C:\xampp\htdocs\petalokasiobjek\system\Database\MigrationRunner.php(188): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#8 C:\xampp\htdocs\petalokasiobjek\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#9 C:\xampp\htdocs\petalokasiobjek\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Migrate->run(Array)
#10 C:\xampp\htdocs\petalokasiobjek\system\CLI\Console.php(37): CodeIgniter\CLI\Commands->run('migrate', Array)
#11 C:\xampp\htdocs\petalokasiobjek\spark(97): CodeIgniter\CLI\Console->run()
#12 {main}
ERROR - 2023-04-26 11:28:25 --> ErrorException: pg_query(): Query failed: ERROR:  relation "tbl_data_point" already exists in C:\xampp\htdocs\petalokasiobjek\system\Database\Postgre\Connection.php:147
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 147)
#1 C:\xampp\htdocs\petalokasiobjek\system\Database\Postgre\Connection.php(147): pg_query(Object(PgSql\Connection), 'CREATE TABLE "t...')
#2 C:\xampp\htdocs\petalokasiobjek\system\Database\BaseConnection.php(691): CodeIgniter\Database\Postgre\Connection->execute('CREATE TABLE "t...')
#3 C:\xampp\htdocs\petalokasiobjek\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE "t...')
#4 C:\xampp\htdocs\petalokasiobjek\system\Database\Forge.php(546): CodeIgniter\Database\BaseConnection->query('CREATE TABLE "t...')
#5 C:\xampp\htdocs\petalokasiobjek\app\Database\Migrations\2023-04-17-084000_TabelDataPoint.php(48): CodeIgniter\Database\Forge->createTable('tbl_data_point')
#6 C:\xampp\htdocs\petalokasiobjek\system\Database\MigrationRunner.php(877): App\Database\Migrations\TabelDataPoint->up()
#7 C:\xampp\htdocs\petalokasiobjek\system\Database\MigrationRunner.php(188): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#8 C:\xampp\htdocs\petalokasiobjek\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#9 C:\xampp\htdocs\petalokasiobjek\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Migrate->run(Array)
#10 C:\xampp\htdocs\petalokasiobjek\system\CLI\Console.php(37): CodeIgniter\CLI\Commands->run('migrate', Array)
#11 C:\xampp\htdocs\petalokasiobjek\spark(97): CodeIgniter\CLI\Console->run()
#12 {main}
ERROR - 2023-04-26 11:30:43 --> ErrorException: pg_query(): Query failed: ERROR:  relation "tbl_data_point" already exists in C:\xampp\htdocs\petalokasiobjek\system\Database\Postgre\Connection.php:147
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 147)
#1 C:\xampp\htdocs\petalokasiobjek\system\Database\Postgre\Connection.php(147): pg_query(Object(PgSql\Connection), 'CREATE TABLE "t...')
#2 C:\xampp\htdocs\petalokasiobjek\system\Database\BaseConnection.php(691): CodeIgniter\Database\Postgre\Connection->execute('CREATE TABLE "t...')
#3 C:\xampp\htdocs\petalokasiobjek\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE "t...')
#4 C:\xampp\htdocs\petalokasiobjek\system\Database\Forge.php(546): CodeIgniter\Database\BaseConnection->query('CREATE TABLE "t...')
#5 C:\xampp\htdocs\petalokasiobjek\app\Database\Migrations\2023-04-17-084000_TabelDataPoint.php(48): CodeIgniter\Database\Forge->createTable('tbl_data_point')
#6 C:\xampp\htdocs\petalokasiobjek\system\Database\MigrationRunner.php(877): App\Database\Migrations\TabelDataPoint->up()
#7 C:\xampp\htdocs\petalokasiobjek\system\Database\MigrationRunner.php(188): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#8 C:\xampp\htdocs\petalokasiobjek\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#9 C:\xampp\htdocs\petalokasiobjek\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Migrate->run(Array)
#10 C:\xampp\htdocs\petalokasiobjek\system\CLI\Console.php(37): CodeIgniter\CLI\Commands->run('migrate', Array)
#11 C:\xampp\htdocs\petalokasiobjek\spark(97): CodeIgniter\CLI\Console->run()
#12 {main}
ERROR - 2023-04-26 11:36:31 --> ErrorException: pg_query(): Query failed: ERROR:  relation "tbl_data_point" already exists in C:\xampp\htdocs\petalokasiobjek\system\Database\Postgre\Connection.php:147
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'pg_query(): Que...', 'C:\\xampp\\htdocs...', 147)
#1 C:\xampp\htdocs\petalokasiobjek\system\Database\Postgre\Connection.php(147): pg_query(Object(PgSql\Connection), 'CREATE TABLE "t...')
#2 C:\xampp\htdocs\petalokasiobjek\system\Database\BaseConnection.php(691): CodeIgniter\Database\Postgre\Connection->execute('CREATE TABLE "t...')
#3 C:\xampp\htdocs\petalokasiobjek\system\Database\BaseConnection.php(605): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TABLE "t...')
#4 C:\xampp\htdocs\petalokasiobjek\system\Database\Forge.php(546): CodeIgniter\Database\BaseConnection->query('CREATE TABLE "t...')
#5 C:\xampp\htdocs\petalokasiobjek\app\Database\Migrations\2023-04-17-084000_TabelDataPoint.php(48): CodeIgniter\Database\Forge->createTable('tbl_data_point')
#6 C:\xampp\htdocs\petalokasiobjek\system\Database\MigrationRunner.php(877): App\Database\Migrations\TabelDataPoint->up()
#7 C:\xampp\htdocs\petalokasiobjek\system\Database\MigrationRunner.php(188): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#8 C:\xampp\htdocs\petalokasiobjek\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#9 C:\xampp\htdocs\petalokasiobjek\system\CLI\Commands.php(65): CodeIgniter\Commands\Database\Migrate->run(Array)
#10 C:\xampp\htdocs\petalokasiobjek\system\CLI\Console.php(37): CodeIgniter\CLI\Commands->run('migrate', Array)
#11 C:\xampp\htdocs\petalokasiobjek\spark(97): CodeIgniter\CLI\Console->run()
#12 {main}
INFO - 2023-04-26 11:53:48 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2023-04-26 11:53:48 --> The route for "login" cannot be found.
in SYSTEMPATH\HTTP\RedirectResponse.php on line 60.
 1 SYSTEMPATH\HTTP\RedirectResponse.php(60): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('login')
 2 VENDORPATH\codeigniter4\shield\src\Filters\SessionAuth.php(78): CodeIgniter\HTTP\RedirectResponse->route(false)
 3 SYSTEMPATH\Filters\Filters.php(173): CodeIgniter\Shield\Filters\SessionAuth->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 4 SYSTEMPATH\CodeIgniter.php(473): CodeIgniter\Filters\Filters->run('C:\\', 'before')
 5 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
INFO - 2023-04-26 11:54:35 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
CRITICAL - 2023-04-26 11:54:35 --> The route for "login" cannot be found.
in SYSTEMPATH\HTTP\RedirectResponse.php on line 60.
 1 SYSTEMPATH\HTTP\RedirectResponse.php(60): CodeIgniter\HTTP\Exceptions\HTTPException::forInvalidRedirectRoute('login')
 2 VENDORPATH\codeigniter4\shield\src\Filters\SessionAuth.php(78): CodeIgniter\HTTP\RedirectResponse->route(false)
 3 SYSTEMPATH\Filters\Filters.php(173): CodeIgniter\Shield\Filters\SessionAuth->before(Object(CodeIgniter\HTTP\IncomingRequest), null)
 4 SYSTEMPATH\CodeIgniter.php(473): CodeIgniter\Filters\Filters->run('C:\\', 'before')
 5 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
INFO - 2023-04-26 11:56:18 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-04-26 11:56:19 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-04-26 11:57:55 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-04-26 11:57:55 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-04-26 11:57:55 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-04-26 11:58:20 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-04-26 11:58:21 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2023-04-26 11:58:21 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
